#ifndef TRANSDUCERPLOTVERSION_H
#define TRANSDUCERPLOTVERSION_H

#define TRANSDUCER_PLOT_VERSION_MAJOR "1"
#define TRANSDUCER_PLOT_VERSION_MINOR "0"
#define TRANSDUCER_PLOT_VERSION TRANSDUCER_PLOT_VERSION_MAJOR "." TRANSDUCER_PLOT_VERSION_MINOR
#define TRANSDUCER_PLOT_APP_NAME "transducer-plot v" TRANSDUCER_PLOT_VERSION

#endif // TRANSDUCERPLOTVERSION_H
